### ISSUE TITLE
Imports API - Enhance Validation/Cleanup

### ISSUE THREAD

**Issue by mkeller3** [qwikgeo/qwikgeo-api#84]
## Description

Currently there is not much validation that occurs for the imports api. It assumes use will input the correct file types and have clean data. This is not the case in reality. In order to deal with this, we need to add further validation to help produce appropriate errors and clean data automatically for users.

## Tasks

- [x] Validate file types
- [x] Validate header columns for leading and trailing white spaces
- [x] Validate lat lng columns with no data in some columns
- [x] Validate a csv with lat lng data with first column with no lat lng data
- [x] Validate joining to a zip code polygon dataset from a csv with a zip code starting with a zero
